- name: Consul | Create client configuration
  template:
    src: client-config.json.j2
    dest: /etc/consul.d/client/config.json
    owner: consul
    group: consul
    mode: 0644

- name: Consul | Create Systemd Client Service
  template:
    src: client.service.j2
    dest: /etc/systemd/system/consul-client.service
    owner: root
    group: root
    mode: 0755
  notify: reload-systemd

- name: Consul | Register client services
  template:
    src: service.json.j2
    dest: "/etc/consul.d/client/{{ item.key }}.json"
    owner: consul
    group: consul
    mode: 0644
  with_dict: "{{ consul.services | default({}) }}"
  notify: reload-consul-client

- name: Consul | Register client healthchecks
  template:
    src: service-check.json.j2
    dest: "/etc/consul.d/client/{{ item.name }}-check.json"
    owner: consul
    group: consul
    mode: 0644
  with_items: "{{ consul.checks | default([]) }}"
  notify: reload-consul-client

- name: Consul | Start Client Service
  systemd:
    name: consul-client
    state: started
    enabled: yes
