- name: Consul | Preflight Tasks
  include_tasks: preflight.yml
  when: "'consul' in group_names | default([])"

- name: Consul | Server Tasks
  include_tasks: server.yml
  when: "'consul-server' in group_names | default([])"

- name: Consul | Client Tasks
  include_tasks: client.yml
  when: "'consul-client' in group_names | default([])"

- name: Consul | ACL Tasks
  include_tasks: acl.yml
  when:
    - "'consul' in group_names | default([])"
    - consul.acl.acl_master_token is defined
