- name: Consul | Create server configuration
  template:
    src: server-config.json.j2
    dest: "/etc/consul.d/server/config.json"
    owner: consul
    group: consul
    mode: 0644

- name: Consul | Create Systemd Server Service
  template:
    src: server.service.j2
    dest: /etc/systemd/system/consul-server.service
    owner: root
    group: root
    mode: 0755

- name: Consul | Start Server Service
  systemd:
    name: consul-server
    state: started
    enabled: yes
