---
  - name: reload-systemd
    systemd:
      daemon_reload: yes
      
  - name: start-consul-server
    service:
      name: consul-server
      state: started

  - name: restart-consul-server
    service:
      name: consul-server
      state: restarted

  - name: reload-consul-server
    service:
      name: consul-server
      state: reloaded

  - name: start-consul-client
    service:
      name: consul-client
      state: started

  - name: restart-consul-client
    service:
      name: consul-client
      state: restarted

  - name: reload-consul-client
    service:
      name: consul-client
      state: reloaded
